name: Test UDP echo

on:
  schedule:
    - cron: '0 7 * * *'  # Triggers the workflow daily at midnight PST/7 AM UTC
  workflow_dispatch:

jobs: 
  test-udp-echo-sanity:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout repository
      uses: actions/checkout@v4
      with: 
        path: beehive

    - name: Setup Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Setup dependencies
      run: |
        ./beehive/ci/dependencies.sh

    - name: Setup Verilator
      uses: actions/checkout@v4
      with:
        repository: verilator/verilator
        ref: stable
        path: verilator

    - name: Build Verilator
      run: |
          cd verilator
          autoconf
          ./configure
          make -j
          export VERILATOR_ROOT=$PWD
          export PATH=$VERILATOR_ROOT/bin:$PATH

    - name: Source settings
      run: source settings.sh

    - name: Setup experiment
      run: |
        cd cocotb_testing/udp_echo
        make init_fusesoc
        make gen_filelist

    - name: Run experiment
      run: make
    
