name: Test UDP echo

on:
  schedule:
    - cron: '0 7 * * *'  # Triggers the workflow daily at midnight PST/7 AM UTC
  workflow_dispatch:

env:        
  VERILATOR_ROOT: $GITHUB_WORKSPACE/verilator
  PATH: $VERILATOR_ROOT/bin:$PATH
  SIM: verilator

jobs: 
  test-udp-echo-sanity:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout repository
      uses: actions/checkout@v4
      with: 
        path: beehive

    - name: Setup Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Setup dependencies
      run: |
        ./beehive/ci/dependencies.sh

    - name: Restore Verilator
      uses: actions/cache/restore@v3
      id: cache
      with:
        path: verilator
        key: verilator

    - name: Check cache hit
      if: steps.cache.outputs.cache-hit != 'true'
      run: exit 1

    - name: Setup env variables
      run: |
        cd verilator

        cd ..

    - name: Source settings
      run: |
        cd beehive
        source settings.sh

    - name: Get submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup experiment
      run: |
        cd cocotb_testing/udp_echo
        export SIM=verilator
        make init_fusesoc
        make gen_filelist

    - name: Run experiment
      run: make
    
